apiVersion: apps/v1
kind: Deployment
metadata:
  name: iot-dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iot-dashboard
  template:
    metadata:
      labels:
        app: iot-dashboard
    spec:
      containers:
      - name: iot-dashboard
        image: snehapadgaonkar/iot-dashboard:latest
        ports:
        - containerPort: 80
        env:
        - name: REACT_APP_BACKEND_URL
          value: "http://localhost:30080"
---
apiVersion: v1
kind: Service
metadata:
  name: iot-dashboard-service
spec:
  selector:
    app: iot-dashboard
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30081
  type: NodePort